<a href="https://colab.research.google.com/github/oliseh6123/TensorflowPractice/blob/main/TensorflowPrac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.8.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 1.1499156 , -0.29060316, -0.21942717, -0.40500152,  0.07429075,
         0.31543294,  0.7918554 , -0.09055144, -0.11349884,  0.11861625]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.24360655, 0.05768722, 0.06194282, 0.05145139, 0.08309044,
        0.10574936, 0.17028855, 0.07046297, 0.06886445, 0.08685631]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.2466836

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2975 - accuracy: 0.9129
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1420 - accuracy: 0.9589
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1071 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0896 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0754 - accuracy: 0.9769


In [ ]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0725 - accuracy: 0.9782 - 552ms/epoch - 2ms/step


[0.0724816843867302, 0.9782000184059143]

In [ ]:
probability_model = tf.keras.Sequential([
                                         model,
                                         tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.65183171e-08, 1.41614835e-08, 1.22452184e-06, 2.14838856e-05,
        5.71441394e-10, 2.43517235e-07, 6.66650573e-14, 9.99970078e-01,
        6.95720459e-08, 6.86598105e-06],
       [3.57218468e-08, 5.95548670e-07, 9.99995589e-01, 3.70516500e-06,
        3.70392195e-19, 5.70502223e-09, 9.72012582e-10, 2.28078385e-12,
        7.17084347e-08, 9.41844786e-17],
       [2.59764988e-07, 9.98503685e-01, 3.28540082e-05, 2.68525837e-05,
        3.32537384e-05, 1.61551372e-06, 4.66186029e-05, 1.04504405e-03,
        3.09761381e-04, 5.30664650e-08],
       [9.99865651e-01, 5.34519700e-07, 1.39355973e-06, 2.43390446e-06,
        1.41794175e-07, 1.28668353e-05, 1.15905495e-04, 5.94975177e-07,
        5.03900310e-10, 4.38549847e-07],
       [3.34610991e-06, 3.77810894e-09, 1.83557256e-06, 5.12180556e-08,
        9.97253954e-01, 4.38863253e-06, 6.98481074e-07, 1.43394418e-05,
        2.44673356e-06, 2.71895994e-03]], dtype=float32)>